/*
 * This source file was generated by the Gradle 'init' task
 */
package com.post.console

import com.post.console.post.application.CreatePostUseCases
import com.post.console.post.application.GetPostUseCases
import com.post.console.post.infrastructure.console.PostConsoleAdapter
import com.post.console.post.infrastructure.databases.InMemoryPostRepository
import com.post.console.user.application.CreateUseCases
import com.post.console.user.application.GetUseCases
import com.post.console.user.application.UpdateUseCases
import com.post.console.user.infrastructure.console.UserConsoleAdapter
import com.post.console.user.infrastructure.databases.InMemoryUserRepository
import com.post.console.comment.infrastructure.databases.InMemoryCommentRepository
import com.post.console.comment.infrastructure.console.CommentConsoleAdapter
import com.post.console.comment.application.CreateCommentUseCases
import com.post.console.comment.application.GetCommentUseCases

fun main() {

    val userRepository = InMemoryUserRepository()
    val postRepository = InMemoryPostRepository()
    val commentRepository = InMemoryCommentRepository()
    val createUseCases = CreateUseCases(userRepository)
    val getUseCases = GetUseCases(userRepository)
    val updateUseCases = UpdateUseCases(userRepository)
    val createPostUseCases = CreatePostUseCases(postRepository)
    val getPostUseCases = GetPostUseCases(postRepository)
    val createCommentUseCases = CreateCommentUseCases(commentRepository)
    val getCommentUseCases = GetCommentUseCases(commentRepository)

    val userConsole =
            UserConsoleAdapter(
                    createPort = createUseCases,
                    getPort = getUseCases,
                    updatePort = updateUseCases
            )

    val postConsole = PostConsoleAdapter(createPost = createPostUseCases, getPort = getPostUseCases)

    val commentConsole = CommentConsoleAdapter(createCommentInputPort = createCommentUseCases, getCommentInputPort = getCommentUseCases)

    while (true) {
        println(
                """
            What module do you want to select:
            1) User
            2) Post
            3) Comment
            0) exit
            """.trimIndent()
        )

        val line = readlnOrNull()?.trim()
        if (line == "0") {
            break
        }

        when (line) {
            "1" -> userConsole.run()
            "2" -> postConsole.run()
            "3" -> commentConsole.run()
            else -> println("Unknown command")
        }
    }
}
