/*
 * This source file was generated by the Gradle 'init' task
 */
package com.post.console

import com.post.console.user.infrastructure.console.UserConsoleAdapter
import com.post.console.user.application.ports.input.CreateUserInputPort
import com.post.console.user.application.CreateUseCases
import com.post.console.user.infrastructure.databases.InMemoryUserRepository
import com.post.console.user.application.ports.input.GetUserInputPort
import com.post.console.user.application.GetUseCases
import com.post.console.user.application.UpdateUseCases

fun main() {
    
    val userRepository = InMemoryUserRepository()
    val createUseCases = CreateUseCases(userRepository)
    val getUseCases = GetUseCases(userRepository)
    val updateUseCases = UpdateUseCases(userRepository)

    val userConsole = UserConsoleAdapter(
        createPort = createUseCases,
        getPort = getUseCases,
        updatePort = updateUseCases
    )

     while (true) {
            println(
                    """
            What module do you want to select:
            1) User
            0) exit
            """.trimIndent()
            )

            val line = readlnOrNull()?.trim()
            if (line == "0") {
                break
            }

            when (line) {
                "1" -> userConsole.run()
                else -> println("Unknown command")
            }
        }
}
